### DAY-1

### we can create an array of various dimenssions 1D,2D,3D,5D,..
### We can also take scalar values to create numpy array

In [1]:
import numpy as np
ar = np.array(12)

In [2]:
ar

array(12)

#### one dimensional

In [4]:
ar1 = np.array([1, 2, 3, 4, 5])
ar1

array([1, 2, 3, 4, 5])

#### two dimensional array creation

In [5]:

ar2 = np.array([[1,2,3],[4,5,6]])
ar2

array([[1, 2, 3],
       [4, 5, 6]])

three dimensional array creation

In [6]:

ar3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
ar3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

#### we can mention our own dimenssions in an array by using "ndim" attribute

In [7]:

ar1.ndim

1

In [8]:
ar2.ndim

2

In [9]:
ar3.ndim

3

In [11]:
ar1 = np.array([1, 2, 3, 4, 5], ndmin=2)
ar1

array([[1, 2, 3, 4, 5]])

In [12]:
ar1.ndim

2

In [13]:

ar1 = np.array([1, 2, 3, 4, 5], ndmin=3)
ar1

array([[[1, 2, 3, 4, 5]]])

In [14]:
ar1.ndim

3

## Numpy Attributes
#### ->np.dtype
#### ->np.shape
#### ->np.itemsize
#### ->np.ndim
#### ->np.nbytes

In [ ]:

ar1 = np.array([1, 2, 3, 4, 5])
ar2 = np.array([[1,2,3],[4,5,6]])
ar3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]) 

In [18]:
ar1.ndim

1

In [19]:
ar2.ndim

2

In [20]:
ar3.ndim

3

In [23]:
#(plates, rows, columns)
print("ar1: ", ar1.shape)
print("ar2: ", ar2.shape)
print("ar3: ", ar3.shape)

ar1:  (5,)
ar2:  (2, 3)
ar3:  (2, 2, 3)


In [24]:
print("ar1: ", ar1.dtype)
print("ar2: ", ar2.dtype)
print("ar3: ", ar3.dtype)

ar1:  int64
ar2:  int64
ar3:  int64


In [ ]:
#(plates, rows, columns, depth)
ar4 = np.array([1, 2, 3, 4, 5], ndmin=4)
print("ar4: ", ar4.shape)
print("ar4: ", ar4.ndim)
print("ar4: ", ar4.dtype)

ar4:  (1, 1, 1, 5)
ar4:  4
ar4:  int64


#### we can create array of float types as well

In [27]:
ar5 = np.array([1.2, 3.5, 4.5])
ar5.dtype

dtype('float64')

## creating an Array using Functions
### functions using which we can create diferent types of arrays

#### ->np.zeros(x)
#### ->np.ones(x)
#### ->np.empty(x)
#### ->np.eye(3)
#### ->np.arange(start,end,step)
#### ->np.linspace(0,10,num=5)

### np.zeros(X)

In [29]:
import numpy as np

In [34]:
ar = np.zeros(3)
print(ar)
print(ar.dtype)
print(ar.ndim)

[0. 0. 0.]
float64
1


In [33]:
ar2 = np.zeros((3, 4))
print(ar2)
print(ar2.dtype)
print(ar2.ndim)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
float64
2


In [35]:
ar3 = np.zeros((3, 4, 5))
print(ar3)
print(ar3.dtype)
print(ar3.ndim)

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]
float64
3


### np.ones(x)

In [36]:
import numpy as np

In [37]:
ar = np.ones(3)
print(ar)
print(ar.dtype)
print(ar.ndim)

[1. 1. 1.]
float64
1


In [38]:
ar2 = np.ones((3, 4))
print(ar2)
print(ar2.dtype)
print(ar2.ndim)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
float64
2


In [39]:
ar3 = np.ones((2, 3, 4))
print(ar3)
print(ar3.dtype)
print(ar3.ndim)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
float64
3


### np.empty(x)
#### --the elements inside the array can be anything its also called garbage values

In [40]:
import numpy as np

In [41]:
ar = np.empty(3)
print(ar)
print(ar.dtype)
print(ar.ndim)

[7.74860419e-304 7.74860419e-304 7.74860419e-304]
float64
1


In [44]:
ar2 = np.empty((3, 5))
print(ar2)
print(ar2.dtype)
print(ar2.ndim)

[[0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000
  0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000
  0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000
  6.81019663e-310]]
float64
2


In [ ]:
# meaningful values, but the shape and type are not correct
ar3 = np.empty((3, 3, 4))
print(ar3)
print(ar3.dtype)
print(ar3.ndim)

[[[8.06755464e-312 8.06751228e-312 0.00000000e+000 0.00000000e+000]
  [0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000]
  [0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000]]

 [[0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000]
  [0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000]
  [0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000]]

 [[0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000]
  [0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000]
  [0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000]]]
float64
3


In [ ]:
#meaningless values and the shape and type are correct
ar3 = np.empty((2, 3, 4))
print(ar3)
print(ar3.dtype)
print(ar3.ndim)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
float64
3


### np.eye()
##### -used for creating identity values where diagonal values in a matrix is 1,only 1 parameter must be given in this method

In [48]:
import numpy as np

In [49]:
ar = np.eye(4)
print(ar)
print(ar.dtype)
print(ar.ndim)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
float64
2


In [52]:
ar = np.eye(12)
print(ar)
print(ar.dtype)
print(ar.ndim)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
float64
2


## np.diag(x)
#### -it will create a square matrix with give elemets as diagonals

In [53]:
import numpy as np

In [54]:
ar = np.diag([1, 2, 3, 4, 5])
print(ar)
print(ar.dtype)
print(ar.ndim)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]
int64
2


In [55]:
ar = np.diag([1, 2, 3])
print(ar)
print(ar.dtype)
print(ar.ndim)

[[1 0 0]
 [0 2 0]
 [0 0 3]]
int64
2


## np.arange(start:end:step)
### -same as range function

In [56]:
import numpy as np

In [57]:
ar = np.arange(10)
print(ar)
print(ar.dtype)
print(ar.ndim)

[0 1 2 3 4 5 6 7 8 9]
int64
1


In [58]:
ar = np.arange(0,10,2)
print(ar)
print(ar.dtype)
print(ar.ndim)

[0 2 4 6 8]
int64
1


## np.linspace(start:end:no.of.parts)
#### -fill elements between start to end with given no.of.equal parts

In [59]:
import numpy as np

In [60]:
ar = np.linspace(0, 10, 5)
print(ar)

[ 0.   2.5  5.   7.5 10. ]


## NUMPY DATA TYPES
#### -> b-byte
#### -> B-unsigned byte
#### -> i-integer
#### -> f-float
#### -> F-Complex Float
#### -> m-timedELta
#### -> M-datetime
#### -> O-object
#### ->S-string
#### ->U-Unicode String
#### ->?-bolean

In [61]:
import numpy as np

In [62]:
ar = np.array([1, 2, 3, 4, 5],'b')
print(ar)
print(ar.dtype)

[1 2 3 4 5]
int8


In [ ]:
#it ranges from -128 to 127
ar = np.array([1, 2, 3, 4, 129],'b')

OverflowError: Python integer 129 out of bounds for int8

In [ ]:
#it ranges from 0 to 255
ar = np.array([1, 2, 3, 4, 129],'B')
print(ar)
print(ar.dtype)

[  1   2   3   4 129]
uint8


#### signed and unsigned

In [67]:
import numpy as np

In [68]:
ar = np.array([1, 2, 3, 4, 5],'i')
ar.dtype

dtype('int32')

In [69]:
ar = np.array([1, 2, 3, 4, 5],'I')
ar.dtype

dtype('uint32')

#### float and unsigned float

In [70]:
import numpy as np

In [73]:
ar = np.array([1, 2, 3, 4, 5],'f')
print(ar)
ar.dtype

[1. 2. 3. 4. 5.]


dtype('float32')

In [74]:
ar = np.array([1, 2, 3, 4, 5],'F')
print(ar)
ar.dtype

[1.+0.j 2.+0.j 3.+0.j 4.+0.j 5.+0.j]


dtype('complex64')

### O- will convert it into pyton object
### S- will convert it into byte string
### U- it is a unicode character

## NUMPY RESHAPE
#### -The shape of an array can be reshaped i.e.;we can conert 1Dto 2D,1D to 3D,2D to 3D,etc,..
### this is done by a calling a function reshape available in numpy module

In [75]:
import numpy as np

In [80]:
ar = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10,11,12])
print(ar.shape)
print(ar.ndim)

(12,)
1


In [84]:
ar.reshape(3,4) ##the change is temporary

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [85]:
print("ar1: ", ar.ndim)

ar1:  1


In [ ]:
ar #the change is temporary

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

#### to make changes permanenet

In [86]:
import numpy as np

In [87]:
ar = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10,11,12])
ar.shape

(12,)

In [88]:
ar.shape

(12,)

In [91]:
ar = ar.reshape(3,4) #the make change  permanent
print(ar)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [92]:
ar # the change is permanent

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

#### now we will reshape this array

In [93]:
import numpy as np

In [94]:
ar = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10,11,12])
ar

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
ar = ar.reshape(3,4) #converting 1D array to 2D array
ar

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [96]:
ar

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [97]:
ar = ar.reshape(4,3)
ar

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [98]:
ar

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
ar =ar.reshape(2,3,2) #converting 2D array to 3D array
ar

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

### np.flatten()
#### -this can convert any array into a 1D array

In [102]:
import numpy as np

In [ ]:
ar.flatten() #converting 3D array to 1D array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])