### DAY-1

### we can create an array of various dimenssions 1D,2D,3D,5D,..
### We can also take scalar values to create numpy array

In [1]:
import numpy as np
ar = np.array(12)

In [2]:
ar

array(12)

#### one dimensional

In [4]:
ar1 = np.array([1, 2, 3, 4, 5])
ar1

array([1, 2, 3, 4, 5])

#### two dimensional array creation

In [5]:

ar2 = np.array([[1,2,3],[4,5,6]])
ar2

array([[1, 2, 3],
       [4, 5, 6]])

three dimensional array creation

In [6]:

ar3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
ar3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

#### we can mention our own dimenssions in an array by using "ndim" attribute

In [7]:

ar1.ndim

1

In [8]:
ar2.ndim

2

In [9]:
ar3.ndim

3

In [11]:
ar1 = np.array([1, 2, 3, 4, 5], ndmin=2)
ar1

array([[1, 2, 3, 4, 5]])

In [12]:
ar1.ndim

2

In [13]:

ar1 = np.array([1, 2, 3, 4, 5], ndmin=3)
ar1

array([[[1, 2, 3, 4, 5]]])

In [14]:
ar1.ndim

3

## Numpy Attributes
#### ->np.dtype
#### ->np.shape
#### ->np.itemsize
#### ->np.ndim
#### ->np.nbytes

In [ ]:

ar1 = np.array([1, 2, 3, 4, 5])
ar2 = np.array([[1,2,3],[4,5,6]])
ar3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]) 

In [18]:
ar1.ndim

1

In [19]:
ar2.ndim

2

In [20]:
ar3.ndim

3

In [23]:
#(plates, rows, columns)
print("ar1: ", ar1.shape)
print("ar2: ", ar2.shape)
print("ar3: ", ar3.shape)

ar1:  (5,)
ar2:  (2, 3)
ar3:  (2, 2, 3)


In [24]:
print("ar1: ", ar1.dtype)
print("ar2: ", ar2.dtype)
print("ar3: ", ar3.dtype)

ar1:  int64
ar2:  int64
ar3:  int64


In [ ]:
#(plates, rows, columns, depth)
ar4 = np.array([1, 2, 3, 4, 5], ndmin=4)
print("ar4: ", ar4.shape)
print("ar4: ", ar4.ndim)
print("ar4: ", ar4.dtype)

ar4:  (1, 1, 1, 5)
ar4:  4
ar4:  int64


#### we can create array of float types as well

In [27]:
ar5 = np.array([1.2, 3.5, 4.5])
ar5.dtype

dtype('float64')